<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Launch Sites Locations Analysis with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:
- **TASK 1:** Mark all launch sites on a map
- **TASK 2:** Mark the success/failed launches for each site on the map
- **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [3]:
# Cell 1: Install required packages
!pip install folium pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: folium in C:\Users\c8578\AppData\Roaming\Python\Python314\site-packages (0.20.0)
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: branca>=0.6.0 in C:\Users\c8578\AppData\Roaming\Python\Python314\site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in C:\ProgramData\anaconda3\Lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in C:\ProgramData\anaconda3\Lib\site-packages (from folium) (2.4.6)
Requirement already satisfied: requests in C:\ProgramData\anaconda3\Lib\site-packages (from folium) (2.34.2)
Requirement already satisfied: xyzservices in C:\ProgramData\anaconda3\Lib\site-packages (from folium) (2026.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: MarkupSafe>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->folium) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->folium) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->folium) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->folium) (2026.7.22)

In [4]:
# Cell 2: Import libraries
import folium
import pandas as pd
from folium.plugins import MarkerCluster, MousePosition
from folium.features import DivIcon

In [5]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/DV0101EN-3-5-1-Generating-Maps-in-Python-py-v2.0.ipynb)

## Task 1: Mark all launch sites on a map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [7]:

dataset_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
spacex_df = pd.read_csv(dataset_url)

Now, you can take a look at what are the coordinates for each site.

In [8]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [9]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [10]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

_TODO:_  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [12]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

for index, row in launch_sites_df.iterrows():
    coord = [row['Lat'], row['Long']]
    
    # Add circle outline
    circle = folium.Circle(coord, radius=1000, color='#d35400', fill=True).add_child(
        folium.Popup(row['Launch Site'])
    )
    
    # Add custom label marker
    marker = folium.map.Marker(
        coord,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12; color:#d35400;"><b>{row["Launch Site"]}</b></div>'
        )
    )
    
    site_map.add_child(circle)
    site_map.add_child(marker)

site_map

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:
- Are all launch sites in proximity to the Equator line?
- Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

# Task 2: Mark the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [13]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records. 
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [14]:
marker_cluster = MarkerCluster()

In [16]:
# Function to assign color based on launch outcome (class 1 = green, class 0 = red)
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'

# Add the missing marker_color column to spacex_df
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)

_TODO:_ Create a new column in `launch_sites` dataframe called `marker_color` to store the marker colors based on the `class` value

In [17]:
site_map.add_child(marker_cluster)

for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color='white', icon_color=record['marker_color']),
        popup=record['Launch Site']
    )
    marker_cluster.add_child(marker)

site_map

In [18]:
# Function to assign color to launch outcome
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'
    
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

_TODO:_ For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [19]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

# TASK 3: Calculate the distances between a launch site to its proximities

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [20]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

You can calculate the distance between two points on the map based on their `Lat` and `Long` values using the following method:

In [21]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [25]:
# Example: CCAFS SLC-40 site and nearby coastline coordinates
site_lat, site_lon = 28.56319, -80.57683
coastline_lat, coastline_lon = 28.56367, -80.56802

# Calculate distance
distance_coastline = calculate_distance(site_lat, site_lon, coastline_lat, coastline_lon)

# Distance display marker
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12; color:#d35400;"><b>{distance_coastline:.2f} KM</b></div>'
    )
)

# Connect launch site to coastline point
lines = folium.PolyLine(
    locations=[[site_lat, site_lon], [coastline_lat, coastline_lon]], 
    weight=1
)

site_map.add_child(distance_marker)
site_map.add_child(lines)
site_map

_TODO:_ Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

_TODO:_ After obtained its coordinate, create a `folium.Marker` to show the distance

In [27]:
# 1. Define launch site and coastline coordinates (e.g., CCAFS SLC-40)
launch_site_lat, launch_site_lon = 28.56319, -80.57683
coastline_lat, coastline_lon = 28.56367, -80.56802

# 2. Calculate distance using the calculate_distance function
distance = calculate_distance(
    launch_site_lat, launch_site_lon, coastline_lat, coastline_lon
)
coordinate = [coastline_lat, coastline_lon]

# 3. Create the marker displaying distance on the map
distance_marker = folium.Marker(
    coordinate,
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12; color:#d35400;"><b>{distance:.2f} KM</b></div>',
    ),
)

# 4. Add marker to the site map
site_map.add_child(distance_marker)
site_map

_TODO:_ Draw a `PolyLine` between a launch site to the selected coastline point

In [29]:
# 1. Define the launch site and coastline points (e.g., CCAFS SLC-40)
launch_site_lat, launch_site_lon = 28.56319, -80.57683
coastline_lat, coastline_lon = 28.56367, -80.56802

# 2. Store the pair of coordinates as a list
coordinates = [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]]

# 3. Create the PolyLine object and add it to the map
lines = folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

_TODO:_ Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [ ]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

In [30]:
# 1. Define Launch Site coordinates (CCAFS SLC-40)
launch_site_lat, launch_site_lon = 28.56319, -80.57683

# 2. Define coordinates for proximities
proximities = {
    'Highway': [28.5632, -80.5707],
    'Railway': [28.5721, -80.58527],
    'City (Titusville)': [28.6122, -80.8075]
}

# 3. Calculate distance, add marker, and draw polyline for each proximity
for name, point in proximities.items():
    # Calculate distance using your helper function
    dist = calculate_distance(launch_site_lat, launch_site_lon, point[0], point[1])
    
    # Create distance label marker
    marker = folium.Marker(
        location=point,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12; color:#d35400;"><b>{dist:.2f} KM ({name})</b></div>'
        )
    )
    site_map.add_child(marker)
    
    # Draw polyline connecting launch site to the proximity point
    line = folium.PolyLine(
        locations=[[launch_site_lat, launch_site_lon], point],
        weight=1,
        color='blue'
    )
    site_map.add_child(line)

site_map

In [32]:
!pip install dash pandas plotly

Defaulting to user installation because normal site-packages is not writeable
Collecting dash
  Downloading dash-4.4.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: plotly in C:\ProgramData\anaconda3\Lib\site-packages (6.7.0)
Requirement already satisfied: Flask<3.2,>=1.0.4 in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (3.1.3)
Requirement already satisfied: Werkzeug<3.2 in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (3.1.6)
Requirement already satisfied: importlib-metadata in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (8.7.1)
Requirement already satisfied: typing_extensions>=4.1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (4.16.0)
Requirement already satisfied: requests in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (2.34.2)
Collecting retrying (from dash)
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: nest-asyncio in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (1.5.1)
Requirement already satisfied: setuptools in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (83.0.0)
Collecting janus>=1.0.0 (from dash)
  Downloading janus-2.0.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic>=2.10 in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (2.13.4)
Requirement already satisfied: comm in C:\ProgramData\anaconda3\Lib\site-packages (from dash) (0.2.3)
Requirement already satisfied: blinker>=1.9.0 in C:\ProgramData\anaconda3\Lib\site-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: click>=8.1.3 in C:\ProgramData\anaconda3\Lib\site-packages (from Flask<3.2,>=1.0.4->dash) (8.4.1)
Requirement already satisfied: itsdangerous>=2.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in C:\ProgramData\anaconda3\Lib\site-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from Flask<3.2,>=1.0.4->dash) (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: narwhals>=1.15.1 in C:\ProgramData\anaconda3\Lib\site-packages (from plotly) (2.23.0)
Requirement already satisfied: packaging in C:\ProgramData\anaconda3\Lib\site-packages (from plotly) (26.3)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click>=8.1.3->Flask<3.2,>=1.0.4->dash) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=2.10->dash) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=2.10->dash) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=2.10->dash) (0.4.2)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: zipp>=3.20 in C:\ProgramData\anaconda3\Lib\site-packages (from importlib-metadata->dash) (3.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->dash) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->dash) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->dash) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\ProgramData\anaconda3\Lib\site-packages (from requests->dash) (2026.7.22)
Downloading dash-4.4.1-py3-none-any.whl (8.9 MB)
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.9 MB 4.8 MB/s eta 0:00:02
   -------------- ------------------------- 3.1/8.9 MB 10.7 MB/s eta 0:00:01
   ------------------------- -------------- 5.8/8.9 MB 12.0 MB/s eta 0:00:01
   ------------------------------------ --- 8.1/8.9 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 8.9/8.9 MB 11.2 MB/s  0:00:00
Downloading janus-2.0.0-py3-none-any.whl (12 kB)
Downloading retrying-1.4.2-py3-none-any.whl (10 kB)
Installing collected packages: retrying, janus, dash

   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   -------------------------- ------------- 2/3 [dash]
   ---------------------------------------- 3/3 [dash]

Successfully installed dash-4.4.1 janus-2.0.0 retrying-1.4.2

  WARNING: The scripts dash-generate-components.exe, dash-update-components.exe, plotly.exe and renderer.exe are installed in 'C:\Users\c8578\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [33]:
# 1. Load dataset directly from URL
import pandas as pd
import dash
from dash import html, dcc
from dash.dependencies import Input, Output
import plotly.express as px

dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_dash.csv"
spacex_df = pd.read_csv(dataset_url)

max_payload = spacex_df['Payload Mass (kg)'].max()
min_payload = spacex_df['Payload Mass (kg)'].min()

# 2. Initialize Dash App
app = dash.Dash(__name__)

# 3. Layout Setup
app.layout = html.Div(children=[
    html.H1(
        'SpaceX Launch Records Dashboard',
        style={'textAlign': 'center', 'color': '#503D36', 'font-size': 40}
    ),
    
    dcc.Dropdown(
        id='site-dropdown',
        options=[
            {'label': 'All Sites', 'value': 'ALL'},
            {'label': 'CCAFS LC-40', 'value': 'CCAFS LC-40'},
            {'label': 'VAFB SLC-4E', 'value': 'VAFB SLC-4E'},
            {'label': 'KSC LC-39A', 'value': 'KSC LC-39A'},
            {'label': 'CCAFS SLC-40', 'value': 'CCAFS SLC-40'}
        ],
        value='ALL',
        placeholder="Select a Launch Site here",
        searchable=True
    ),
    html.Br(),

    html.Div(dcc.Graph(id='success-pie-chart')),
    html.Br(),

    html.P("Payload range (Kg):"),
    dcc.RangeSlider(
        id='payload-slider',
        min=0,
        max=10000,
        step=1000,
        marks={
            0: '0',
            2500: '2500',
            5000: '5000',
            7500: '7500',
            10000: '10000'
        },
        value=[min_payload, max_payload]
    ),
    html.Br(),

    html.Div(dcc.Graph(id='success-payload-scatter-chart')),
])

# 4. Pie Chart Callback
@app.callback(
    Output(component_id='success-pie-chart', component_property='figure'),
    Input(component_id='site-dropdown', component_property='value')
)
def get_pie_chart(entered_site):
    if entered_site == 'ALL':
        fig = px.pie(
            spacex_df,
            values='class',
            names='Launch Site',
            title='Total Success Launches By Site'
        )
        return fig
    else:
        filtered_df = spacex_df[spacex_df['Launch Site'] == entered_site]
        df_counts = filtered_df['class'].value_counts().reset_index()
        df_counts.columns = ['class', 'count']
        fig = px.pie(
            df_counts,
            values='count',
            names='class',
            title=f'Total Success Launches for site {entered_site}'
        )
        return fig

# 5. Scatter Plot Callback
@app.callback(
    Output(component_id='success-payload-scatter-chart', component_property='figure'),
    [
        Input(component_id='site-dropdown', component_property='value'),
        Input(component_id='payload-slider', component_property='value')
    ]
)
def get_scatter_chart(entered_site, payload_range):
    low, high = payload_range
    filtered_df = spacex_df[
        (spacex_df['Payload Mass (kg)'] >= low) & 
        (spacex_df['Payload Mass (kg)'] <= high)
    ]
    
    if entered_site == 'ALL':
        fig = px.scatter(
            filtered_df,
            x='Payload Mass (kg)',
            y='class',
            color='Booster Version Category',
            title='Correlation between Payload and Success for all Sites'
        )
        return fig
    else:
        site_df = filtered_df[filtered_df['Launch Site'] == entered_site]
        fig = px.scatter(
            site_df,
            x='Payload Mass (kg)',
            y='class',
            color='Booster Version Category',
            title=f'Correlation between Payload and Success for site {entered_site}'
        )
        return fig

# 6. Run Inline inside Jupyter Notebook
app.run(mode='inline', port=8050)

After you plot distance lines to the proximities, you can answer the following questions easily:
- Are launch sites in close proximity to railways?
- Are launch sites in close proximity to highways?
- Are launch sites in close proximity to coastline?
- Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Yan Luo](https://www.linkedin.com/in/yan-luo-96288783/)

### Other Contributors

Joseph Santarcangelo

## Change Log

|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2021-05-26|1.0|Yan|Created the initial version|

Copyright © 2021 IBM Corporation. All rights reserved.